- name: Copy check for user script
  template:
    src: templates/check_for_user.py
    dest: "{{ script_temp_location }}/check_for_user.py"
    owner: "{{ oracle_user }}"
    group: "{{ oracle_group }}"

- name: Call check for user script
  shell: "{{ wlst_script }} {{ script_temp_location }}/check_for_user.py"
  register: check_for_user_reg
  ignore_errors: True

- debug: var=check_for_user_reg.rc
