- name: Check for user existance
  include: check_for_user.yml

- name: Create weblogic user
  include: create_user.yml
  when: 
    - create_user 
    - not user_exists

- name: Check for group membership
  include: check_for_membership.yml
  when: update_memberships

- name: Update group memberships
  include: update_memberships.yml
  when: 
    - update_memberships
    - not is_member
